### ISSUE TITLE
Rename the repo to PowerEdu.jl

### ISSUE THREAD

**Issue by Realife-Brahmin** [ninadkgaikwad/PowerEdu#3]
Go to Settings and the first thing you're gonna see is the option to rename our repo. Here's an example from one of my own repos:
![image](https://github.com/ninadkgaikwad/PowerSystemsAnalysis/assets/24756405/d9c18b5c-dc15-4132-a3e8-307550c9e29d)

**Comment by ninadkgaikwad** [comment]
Change made
